import type { Brand, Program, ProgramType } from "./types";

export const initialBrands: Brand[] = ["INFINIX", "IPHONE", "ITEL", "NUBIA", "OPPO", "REALME", "SAMSUNG", "TECNO", "VIVO", "XIAOMI"];
export const initialProgramTypes: ProgramType[] = ["Aktivasi", "Cashback", "MDR", "Monthly", "PWP", "Refund", "Sell In", "Sell Out", "Weekly"];

export const initialPrograms: Program[] = [
  {
    id: "PROG-001",
    programType: "Sell Out",
    brand: "SAMSUNG",
    description: "Galaxy S24 Series Launch Campaign",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-07-31"),
    target: 10000,
    achievement: 8500,
    rewardPercentage: 5,
    status: "Active",
    paymentStatus: "Unpaid",
  },
  {
    id: "PROG-002",
    programType: "Cashback",
    brand: "IPHONE",
    description: "iPhone 15 Pro Max Cashback Offer",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    target: 5000,
    achievement: 5500,
    rewardPercentage: 2,
    status: "Ended",
    paymentStatus: "Paid",
  },
  {
    id: "PROG-003",
    programType: "Monthly",
    brand: "XIAOMI",
    description: "Redmi Note 13 Series Monthly Target",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-08-31"),
    target: 20000,
    achievement: 12000,
    rewardPercentage: 3,
    status: "Active",
    paymentStatus: "Unpaid",
  },
  {
    id: "PROG-004",
    programType: "Aktivasi",
    brand: "OPPO",
    description: "Reno 11 Activation Bonus",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-09-30"),
    target: 15000,
    achievement: 2500,
    rewardPercentage: 1.5,
    status: "Pending",
    paymentStatus: "Unpaid",
  },
  {
    id: "PROG-005",
    programType: "Sell In",
    brand: "VIVO",
    description: "V30 Series Channel Stuffing",
    startDate: new Date("2024-05-15"),
    endDate: new Date("2024-07-15"),
    target: 8000,
    achievement: 7800,
    rewardPercentage: 4,
    status: "Active",
    paymentStatus: "Partial",
  },
    {
    id: "PROG-006",
    programType: "Weekly",
    brand: "REALME",
    description: "Realme 12 Pro+ Weekly Sales Sprint",
    startDate: new Date("2024-06-10"),
    endDate: new Date("2024-08-05"),
    target: 2500,
    achievement: 1200,
    rewardPercentage: 5,
    status: "Active",
    paymentStatus: "Unpaid",
  },
];
